# Generated by Django 4.2.6 on 2025-07-27 05:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_paket', models.CharField(choices=[('device', 'Device'), ('pppoe', 'PPPoE')], max_length=10)),
                ('jumlah_device', models.IntegerField(blank=True, null=True)),
                ('kecepatan_mbps', models.IntegerField(blank=True, null=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('kontak', models.CharField(blank=True, max_length=50, null=True)),
                ('username_pppoe', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_bergabung', models.DateField(default=django.utils.timezone.now)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('belum_lunas', 'Belum Lunas'), ('suspend', 'Suspend')], default='aktif', max_length=20)),
                ('lokasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tagihan_app.lokasi')),
                ('paket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tagihan_app.paket')),
            ],
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_tagihan', models.DateField(default=django.utils.timezone.now)),
                ('periode_bulan', models.DateField()),
                ('jumlah_tagihan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('status', models.CharField(choices=[('lunas', 'Lunas'), ('belum_lunas', 'Belum Lunas'), ('tertunggak', 'Tertunggak')], default='belum_lunas', max_length=20)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagihan_app.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateTimeField(default=django.utils.timezone.now)),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagihan_app.tagihan')),
            ],
        ),
    ]
