# Generated by Django 4.2.6 on 2025-07-30 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagihan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='pelanggan',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='tagihan_app.pelanggan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='metode_pembayaran',
            field=models.CharField(choices=[('tunai', 'Tunai'), ('transfer_bank', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('kartu_kredit', 'Kartu Kredit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='tagihan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tagihan_app.tagihan'),
        ),
    ]
