# Generated by Django 4.2.6 on 2025-07-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagihan_app', '0002_pembayaran_bukti_pembayaran_pembayaran_pelanggan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagihan',
            name='jumlah_terbayar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='status',
            field=models.CharField(choices=[('lunas', 'Lunas'), ('belum_lunas', 'Belum Lunas'), ('sebagian_terbayar', 'Sebagian Terbayar'), ('tertunggak', 'Tertunggak')], default='belum_lunas', max_length=20),
        ),
    ]
