# Generated by Django 4.2.6 on 2025-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagihan_app', '0003_tagihan_jumlah_terbayar_alter_tagihan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif'), ('suspend', 'Suspend')], default='aktif', max_length=20),
        ),
    ]
